# نبدأ من صورة freqtrade الرسمية
FROM freqtradeorg/freqtrade:stable

# نسوي مجلد للعمل
WORKDIR /freqtrade

# ننسخ كل ملفات المشروع داخل الكونتينر
COPY . .

# نشغل البوت باستخدام config.json
CMD ["freqtrade", "trade", "--config", "user_data/config.json", "--strategy", "BasicStrategy"]
