# نبدأ من صورة freqtrade الرسمية
FROM freqtradeorg/freqtrade:stable

# نسوي مجلد للعمل
WORKDIR /freqtrade

# ننسخ كل ملفات المشروع داخل الكونتينر
COPY . .

# نشغل البوت باستخدام config.json
CMD ["freqtrade", "trade", "--config", "config.json", "--strategy", "DefaultStrategy"]
